name: CI

env:
  SERVER_NAME: ${{ secrets.AZURE_SQL_SERVER_NAME }}

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: test
      id: gh_ws
      shell: pwsh
      run: |
        $test="$env:DB_Server_Name.database.usgovcloudapi.net"
        echo $test
      env:
          DB_Server_Name: ${{ env.SERVER_NAME }}

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Login to Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy to Azure SQL
    - uses: azure/sql-action@v1
      with:
        server-name: ${{ secrets.AZURE_SQL_SERVER_NAME }}
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        sql-file: 'sql/deploy.sql'
